### PR TITLE
Adding support for smaller favorites, additional room badges and vacuum addons

### PR DESCRIPTION
**Pull request by Seechay**
I'd like to bring in some functional and UI updates that I've been using. There are three new changes introduced in this PR.

1. Smaller favorites
I wanted a way to have favorites on my homepage for easy status or script calling, but on my wall mounted tablets, the current icons take up a ton of space and end up hiding the rooms. This change introduces a user selectable alternate. The icons sit just under the header icons with a smaller form factor.
Normal:
image
Smaller:
image
2. Additional room badges
This change allows users to see the state of custom sensors/devices that aren't defined in the dashboard. You can give a list of binary_sensors, sensors or input_booleans that report "True" or "on" and an icon to display when it is on. My use case was I wanted to be able to at a glance see if a bed is occupied. To demonstrate, I've added a dummy input bool and set it to true.
```
rooms:
  - name: Master Bedroom
    additional_badges:
      - entity: input_boolean.dummy1
        icon: mdi:dumbbell
```
image

3. Vacuum Addon support
This one is more of a quality of life change. I have been using an addon page for my vaccum that adds a bit more functionality, however if the vacuum is not defined in the room and is running, it won't show up in the active devices header or in the devices tab, only the room page. If I wanted to see the status of the vacuum in the header, I needed to define the vacuum in the room, but then this led me to seeing two instances of it; one for the room and one for the room addon. As you can see in the config below, the vacuum is coming from the addon and not the room config.
Devices View:
image
Room config:
```
  - name: Foyer
    icon: mdi:floor-plan
    light: light.foyer_lights
    temperature: sensor.foyer_aqara_temperature
    humidity: sensor.foyer_aqara_humidity
    pressure: sensor.foyer_aqara_pressure
    motion: binary_sensor.foyer_motion
    door: binary_sensor.front_and_garage_doors
    device: switch.magicmirror
    media_player: media_player.echo_flex_hallway
    page_entities:
      entities:
        - entity: input_boolean.foyer_motion
    addons:
      - name: Dwayne
        icon: mdi:robot-vacuum
        path: 'dwains-dashboard/addons/rooms/foyer/vacuum/page.yaml'
        button_path: 'dwains-dashboard/addons/rooms/foyer/vacuum/button.yaml'
        data:
          vacuum: vacuum.robot
          platform: valetudo
          map: camera.map_data
          rooms:
            - room: Living Room
              zone: clean_living_room
              icon: fal:couch
            - room: Kitchen
              zone: clean_kitchen
              icon: fal:refrigerator
            - room: Dining Room
              zone: clean_dining_room
              icon: fal:coffee
            - room: Hallway
              zone: clean_hall
              icon: fal:key-skeleton
            - room: Foyer
              zone: clean_foyer
              icon: fal:warehouse
            - room: Mop
              zone: clean_mop
              icon: mdi:water
          controls:
            - name: Start
              service: vacuum.start
              icon: mdi:play
            - name: Pause
              service: vacuum.pause
              icon: mdi:pause
            - name: Stop
              service: vacuum.stop
              icon: mdi:stop
            - name: Return
              service: vacuum.return_to_base
              icon: mdi:ev-station
            - name: Locate
              service: vacuum.locate
              icon: mdi:map-marker-circle
          sensors:
            - name: Main brush
              sensor: sensor.main_brush
              icon: mdi:broom
            - name: Side brush
              sensor: sensor.right_brush
              icon: mdi:broom
            - name: Filter
              sensor: sensor.main_filter
              icon: mdi:broom
            - name: Sensor
              sensor: sensor.sensor_cleaning
              icon: mdi:air-filter
```

### CODE REVIEW

**Comment by antonoal** [comment]
I’ve addressed the problem #3 by converting room addon for vacuum into an entity pop up addon. Then just added the vaccum to one of the rooms and/or favourites.

**Comment by Seechay** [comment]
@dwainscheeren are you interested in any of these features? If so, I'll fix the merge issues. I can also purge what you don't want or close the PR.

**Comment by dwainscheeren** [comment]
I'm working for some weeks now on dd 3.0 maybe we can integrate it there, first check out how 3.0 rolls out for the dd users :)

**Comment by Seechay** [comment]
> I'm working for some weeks now on dd 3.0 maybe we can integrate it there, first check out how 3.0 rolls out for the dd users :)

I've noticed from some of your other comments and I'm super excited for 3.0 to come out! I haven't found a branch with recent commits on it though. The 3.0 one looks a bit out of date with 2.0. Are you working on it in a private repo?

> Hello, can I ask you how do you integrate the Neato with the addon?

My neato doesn't support zoned or spot cleaning, so I don't use it with the vacuum addon. I just add it as a normal vacuum entity on the room config. My roborock has a lot more functionality, so I opted to use the addon. If your neato is a newer model with more features, you can use [this](https://github.com/dwainscheeren/dwains-dashboard-addons/tree/for-dd-2.0/rooms/vacuum).

**Comment by dwainscheeren** [comment]
> I've noticed from some of your other comments and I'm super excited for 3.0 to come out! I haven't found a branch with recent commits on it though. The 3.0 one looks a bit out of date with 2.0. Are you working on it in a private repo?

Yes, There is a closed alpha on my Discord and I'm working on 3.0 privately because other people are stealing my code and use it for their own dashboard unfortunately.

**Comment by Seechay** [comment]
> > I've noticed from some of your other comments and I'm super excited for 3.0 to come out! I haven't found a branch with recent commits on it though. The 3.0 one looks a bit out of date with 2.0. Are you working on it in a private repo?
> 
> Yes, There is a closed alpha on my Discord and I'm working on 3.0 privately because other people are stealing my code and use it for their own dashboard unfortunately.

Fair enough, don't blame you there! Your dashboard is too nice for it's own good :) it's very polished and should be a native feature of HA imho.

**Comment by bubez81** [comment]
> > I'm working for some weeks now on dd 3.0 maybe we can integrate it there, first check out how 3.0 rolls out for the dd users :)
> 
> I've noticed from some of your other comments and I'm super excited for 3.0 to come out! I haven't found a branch with recent commits on it though. The 3.0 one looks a bit out of date with 2.0. Are you working on it in a private repo?
> 
> > Hello, can I ask you how do you integrate the Neato with the addon?
> 
> My neato doesn't support zoned or spot cleaning, so I don't use it with the vacuum addon. I just add it as a normal vacuum entity on the room config. My roborock has a lot more functionality, so I opted to use the addon. If your neato is a newer model with more features, you can use [this](https://github.com/dwainscheeren/dwains-dashboard-addons/tree/for-dd-2.0/rooms/vacuum).

Yes, my Neato has zones, but the service being called is different than the addon and I haven't been able to change it to work with mine too.

`service: neato.custom_cleaning
data:
  mode: 2
  navigation: 3
  category: 4
  zone: Soggiorno
target:
  entity_id: vacuum.jarvis`

This is an example of how the zone service works

**Pull request closed without merging**
